import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv("data.csv")

In [ ]:
df.columns

Index(['Dehydration', 'Medicine Overdose', 'Acidious', 'Cold ', 'Cough',
       'Dehydration.1', 'Medicine Overdose.1', 'Acidious.1', 'Cold .1',
       'Cough.1', 'Type', 'Temperature', 'Heart Rate', 'Pulse', 'BPSYS',
       'BPDIA', 'Respiratory Rate', 'Oxygen Saturation', 'PH',
       'Causes Respiratory Imbalance'],
      dtype='object')

Dehydration  Medicine Overdose  Acidious  Cold   Cough  Dehydration.1  \
0           False               True      True  False  False              0   
1           False               True     False   True   True              0   
2           False              False     False   True   True              0   
3           False              False     False  False  False              0   
4            True               True      True  False  False              1   
...           ...                ...       ...    ...    ...            ...   
4281        False              False     False  False  False              0   
4282        False               True      True  False  False              0   
4283         True              False      True  False   True              1   
4284        False               True     False   True   True              0   
4285        False               True      True   True  False              0   

      Medicine Overdose.1  Acidious.1  Cold .1  Cough.1  Type  Temperature  \
0                       1           1        0        0     2           98   
1                       1           0        1        1     3          103   
2                       0           0        1        1     2          105   
3                       0           0        0        0     0           98   
4                       1           1        0        0     3           96   
...                   ...         ...      ...      ...   ...          ...   
4281                    0           0        0        0     0           99   
4282                    1           1        0        0     2          103   
4283                    0           1        0        1     3          103   
4284                    1           0        1        1     3          106   
4285                    1           1        1        0     3           96   

      Heart Rate  Pulse  BPSYS  BPDIA  Respiratory Rate  Oxygen Saturation  \
0            100    145    106     51                55               0.97   
1            164     58    106     94                38               0.92   
2            126    109     98     56                11               0.92   
3             84     60    106     63                16               1.00   
4            130    158    100     75                24               0.98   
...          ...    ...    ...    ...               ...                ...   
4281          75     60    116     77                12               1.00   
4282          92    157     98     74                40               0.93   
4283         118    162    102     50                34               0.96   
4284         167    160     99     85                28               0.97   
4285         146     84     97     40                13               0.95   

      PH Causes Respiratory Imbalance  
0     11                       Severe  
1     11                      Chronic  
2     14                       Severe  
3      8                       Normal  
4      4                      Chronic  
...   ..                          ...  
4281   8                       Normal  
4282   8                       Severe  
4283  11                      Chronic  
4284   8                      Chronic  
4285  12                      Chronic  

[4286 rows x 20 columns]

In [ ]:
symptoms = ['Dehydration', 'Medicine Overdose', 'Acidious', 'Cough']


In [ ]:
X = df[symptoms + ['Type', 'Temperature', 'Heart Rate', 'Pulse', 'BPSYS', 'BPDIA', 'Respiratory Rate', 'Oxygen Saturation', 'PH']]
y = df['Causes Respiratory Imbalance']  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)



1.0


In [ ]:
!pip install --upgrade pandas

In [ ]:
all_predictions = model.predict(X)
df['Predicted_Disease'] = all_predictions


In [ ]:
# prompt: cheack the model with test items and get accuracy

from sklearn.metrics import confusion_matrix, accuracy_score

# Get predictions for the test data
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy
print("Accuracy:", accuracy)

# Get the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion matrix:")
print(cm)


Accuracy: 1.0
Confusion matrix:
[[429   0   0   0]
 [  0 122   0   0]
 [  0   0  27   0]
 [  0   0   0 280]]


In [ ]:
import pickle
pickle.dump(df,open('df.pkl','wb'))